site_name: Kubernetes
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - content.code.annotate # I still dont know what this code line does.

nav:
  - Home: index.md
  - History: history.md
  - Introduction: introduction.md
  - Setup Kubectl: setup_kubectl.md
  - Setup Minikube: setup_minikube.md
  - Setup Kops: setup_kops.md