site_name: Kubernetes
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - content.code.annotate # I still dont know what this code line does.

nav:
  - Getting Started:
      - Info: index.md
      - History: history.md
      - Introduction: introduction.md
  - Setup:
      - Setup Kubectl: setup_kubectl.md
      - Setup Minikube: setup_minikube.md
      - Setup Kops: setup_kops.md
  - Concepts:
      - Commands & Arguments: commands_arguments.md
      - Objects: objects.md
      - Namespace: namespaces.md
      - Kube Config: kube_config.md
      - Jobs and Cron Jobs: jobs_cron_jobs.md
      - DaemonSet: daemonset.md
      - Taints and Tolerations: taints_tolerations.md
      - Limits: limits.md
  - Workloads:
      - ReplicaSet: replicaset.md
      - Deployment: deployment.md
      - Service: service.md
      - Volume: volumes.md
      - Config Map: config_map.md
      - Secrets: secrets.md
      - ingress: ingress.md
  - Helm:
      - Introduction: helm_introduction.md
      - Hands On: helm_hands_on.md
      - Helm with AI: helm_with_ai.md
  - EKS: eks_introduction.md

  - Logging:
      - Different Logging: different_logging.md
      - Lens: lens.md
  - Cheat Sheet: cheatsheet.md


plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
